Algoritmo "tabuadaNove"
// Disciplina   : Tecnicas de desenvolvimento de algoritmos
// Professor   : Lidiano
// Descrição   : calcula e imprime a tabuada do nove
// Autor(a)    : Charles Vaghetti
// Data atual  : 11/10/2020
Var
// Seção de Declarações das variáveis 
   i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    para i de 1 ate 10 faca
         escreval("9 x ",i," = ", 9*i)
    fimpara

Fimalgoritmo